extends Node

var methods = [
{
"name":"Waterfall",
"description":"",
"sprintAmount":0,
"sprintLength":0,
"sprintMetricAmount":0,
"randomEventChance":0
},
{
"name":"Agile",
"description":"",
"sprintAmount":0,
"sprintLength":0,
"sprintMetricAmount":0,
"randomEventChance":0
},
{
"name":"Hybrid",
"description":"",
"sprintAmount":0,
"sprintLength":0,
"sprintMetricAmount":0,
"randomEventChance":0
},
{
"name":"V-Model",
"description":"",
"sprintAmount":0,
"sprintLength":0,
"sprintMetricAmount":0,
"randomEventChance":0
},
{
"name":"Spiral",
"description":"",
"sprintAmount":0,
"sprintLength":0,
"sprintMetricAmount":0,
"randomEventChance":0
}
]